[project]
name = "ingestion"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.40.38",
    "pydantic>=2.11.9",
    "requests>=2.32.5",
]
