[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "awswrangler>=3.13.0",
    "streamlit>=1.49.1",
    "streamlit-folium>=0.25.2",
]
